image: alpine/edge
packages:
  - python3
secrets:
  - 88b90083-3598-4b5d-b3dd-3861add21a7d
sources:
  - https://git.sr.ht/~ihabunek/toot
  - https://git.sr.ht/~ihabunek/annotatepy
tasks:
  - deps: |
      pip3 install --user --progress-bar off jedi
      cd annotatepy
      pip3 install --user -e .

  - annotate: |
      cd toot
      /home/build/.local/bin/annotatepy toot -o annotations.json
      cat annotations.json
      ../upload-annotations annotations.json ihabunek toot

  - annotate: |
      cd annotatepy
      python3 setup.py install --user
      cd ../toot
      ~/.local/bin/annotatepy toot > annotations.json
      ../upload-annotations annotations.json ihabunek toot
