image: alpine/edge
packages:
  - python3
  - py3-setuptools
secrets:
  - 88b90083-3598-4b5d-b3dd-3861add21a7d
sources:
  - https://git.sr.ht/~ihabunek/toot
  - https://git.sr.ht/~ihabunek/annotatepy
tasks:
  - annotate: |
      cd annotatepy
      python3 setup.py install --user
      cd ../toot
      ~/.local/bin/annotatepy toot > annotations.json
      ../upload-annotations annotations.json ihabunek toot
