image: debian/bookworm
packages:
  - python3-venv
sources:
  - https://github.com/ihabunek/toot
tasks:
  - test: |
      cd toot
      python3 -m venv venv
      . ./venv/bin/activate
      pip install -e .
      pip install pytest
      pip install psycopg2-binary
      pytest
triggers:
  - action: email
    condition: failure
    to: ivan@habunek.com
